### ISSUE TITLE
item-selected is not working

### ISSUE THREAD

**Issue by AmosSzust** [guastallaigor/vue-horizontal-timeline#102]
**Describe the bug**
Setting the timeline to clickable and setting the item-selected property does not make it work, item-selected is not changed when the user clicks an item.

**To Reproduce**
This is the storybook, make sure clickable is true and click on an item, item-selected content is **not** changed accordingly
https://vue-horizontal-timeline.netlify.app/?path=/story/vuehorizontaltimeline--default
This is my (also not working) code:
```
          <vue-horizontal-timeline
            :items="timelineItems"
            timeline-background="#E1F5FE"
            content-class="timelineFont"
            title-class="timelineTitleFont"
            :item-selected="objectLink"
            :clickable="true"
            @click="someMethod()"
          />
```
In the above case, someMethod is triggered but objectLink remains undefined. Again, story book link shows the same wrong behavior.

**Expected behavior**
item-selected should contain the relevant object

**Screenshots**
I clicked on title exmple 2 item but nothing changed in item-selected
![image](https://user-images.githubusercontent.com/100950035/199672851-12510629-13b3-426d-8072-a3b9f0317123.png)

**Environment:**
 - OS: Windows
 - Browser: Edge
 - Build environment 16.15.0
 - **Vue 3**

**Comment by guastallaigor** [comment]
Hello @AmosSzust, on a Vue 3 project, if you want a property to be reactive, you need to use `v-model:property`, otherwise it won't be.
Also, this component requires for you to pass an unique key attribute for each object inside the items array using the `item-unique-key` prop.

I don't think this is a bug since seems to be working here

```js

<template>
  <vue-horizontal-timeline
    :items="items"
    timeline-background="#E1F5FE"
    content-class="timelineFont"
    title-class="timelineTitleFont"
    v-model:item-selected="objectLink"
    item-unique-key="title"
    :clickable="true"
    @click="someMethod()"
  />
</template>

<script>
import VueHorizontalTimeline from "vue-horizontal-timeline";

export default {
  name: "App",
  components: {
    VueHorizontalTimeline,
  },
  data() {
    const example1 = {
      title: "Title example 1",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const example2 = {
      title: "Title example 2",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const example3 = {
      title: "Title example 3",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const items = [example1, example2, example3];

    return {
      items,
      objectLink: {
        title: "",
        content: "",
      },
    };
  },
  methods: {
    someMethod() {
      console.log("hello");
    },
  },
};
</script>
```

Check this basic example above you'll see. The docs and storybook are both a bit out of dated since unfortunately I don't have much time for OSS anymore.
Let me know if this works, I'll some time to close the issue.

**Comment by AmosSzust** [comment]
I'll be damn, yeah, all I was missing is that v-model:item-selected. I read somewhere that ':' is a shorthand and 'v-model' is not mandatory so I didn't even think of that.

You are right that this is not a bug, I guess a small change in the docs will do the trick. Thanks!
