### ISSUE TITLE
How  can I  get   item-selected  values

### ISSUE THREAD

**Issue by yankai12** [guastallaigor/vue-horizontal-timeline#63]
How  can I  get   item-selected  values

   <vue-horizontal-timeline
            :items="items"
            :item-selected="curItem"
            :clickable="true"
            style="position: absolute; width: 90%"
            @click="currentNode()"
          />
this  is  not  ok

**Comment by guastallaigor** [comment]
Hello @yankai12 

If the `clickable` prop is set to `true`, and your items are valid it should work, just like [Storybook](https://vue-horizontal-timeline.netlify.app/?path=/story/vuehorizontaltimeline--default) in the "Actions" tab and our unit tests.

If this is not working for you, please provide a valid example for me to reproduce your scenario.
Thank you.
