### ISSUE TITLE
Is it possible to set max-height and max-width to this component and customize density of events based on time difference? 

### ISSUE THREAD

**Issue by vbabaria** [guastallaigor/vue-horizontal-timeline#69]
Great, component
looks like it does allow min-width and max-width but couldn't find info on how to set max-height and max-width.

also trying to customize density of the events based on time difference if possible (i.e. shows bigger gap if time difference is high as opposed to small for short time gap between two events) for more intuitive front end.

or i may have missed something if these features already exists - thanks

**Comment by guastallaigor** [comment]
Hello @vbabaria, thank you for the complement.
Right now there's no `max-height` or `max-width` prop to be used.
But you can try to set then directly in your component, using the classes.
See this example below:

```
<template>
  <vue-horizontal-timeline
    :items="items"
    content-substr="99999"
    min-width="0"
  />
</template>

<script>
export default {
  data() {
    const example1 = {
      title: "Title example 1",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const example2 = {
      title: "Title example 2",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const example3 = {
      title: "Title example 3",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ex dolor, malesuada luctus scelerisque ac, auctor vitae risus. Vivamus risus dolor, faucibus a bibendum quis, facilisis eget odio.",
    };
    const items = [example1, example2, example3];

    return { items };
  },
};
</script>

<style>
.vue-horizontal-timeline .timeline .time {
  max-height: 100px;
  max-width: 90px;
  overflow: hidden;
}
/* .vue-horizontal-timeline .timeline .content {
  max-height: 100px;
  max-width: 50px;
} */
</style>
```

![image](https://user-images.githubusercontent.com/22016005/116010076-4947a480-a5f3-11eb-99e7-659032009f5d.png)

If I comment the first style and uncomment the second:

![image](https://user-images.githubusercontent.com/22016005/116010090-5bc1de00-a5f3-11eb-9ab1-1327228cc94e.png)

Hope this helps.

**Comment by vbabaria** [comment]
@guastallaigor - Thanks a lot for the quick response

will give it a try

i am also looking for showing relative gap between two events (smaller gap for shorter time difference and little bit bigger for larger time differences) instead of showing every events on equal distances to make it more intuitive visually.

do you know if current version allows this features? - Thanks again

**Comment by guastallaigor** [comment]
Unfortunately this component does not allow this feature as of this moment.
But if you have an idea on how to do it, contributions are welcomed.

**Comment by guastallaigor** [comment]
Hello @vbabaria 

I added the ability for you to add gaps between each step.
If the `title` and `content` attributes are both empty, and you are not passing any `<slot/>`, then it will add a gap. Pass more empty objects there and you will have a larger gap.
Not the cleanest way of doing I admit, but it will work for now until we find a better way.

I will be closing this issue then, but if you have any problems with that I can reopen it.
