### ISSUE TITLE
Can't find information on how to display a map in content such that each key value appears on a new line

### ISSUE THREAD

**Issue by AbrieJCronje** [guastallaigor/vue-horizontal-timeline#85]
Really cool component, just have two issues with it atm.

In the attached image, you can see the first problem im having with displaying a map in content in the first time step. The second time step has the desired look. (was achieved by simply spacing a single string accordingly)

The other problem can also be seen in the image, I am hoping the reduce the amount of padding between the top/bottom of the background and the top/bottom of the time step items. I've seen in another issue that there is not yet a max-height prop. I tried the styles you posted in that issue but was not successful, could you give an example of how to reduce that padding specifically?

![image](https://user-images.githubusercontent.com/55285437/136941639-ebd510e4-edda-4cfd-a207-670209b7b7fb.png)

**Comment by guastallaigor** [comment]
Hello @AbrieJCronje ,

Thank you. Regarding the first issue, I did not understand the problem. Could you please provide a reproduction link for the issue?

The second issue, in order to remove the padding, have you tried this:

```html
.vue-horizontal-timeline .timeline {
    padding: 0 !important;
}
```

And setting the `timeline-background` prop to whatever you have as your main background-color in your application?

**Comment by AbrieJCronje** [comment]
Dont think a codesandbox would help too much, let me see if I can explain it differently.

The timeline is showing `item` for each `item` in `items`. It is displaying `item.content`

Now, I have data in the form of:
```
data = {
    event: some_event,
    items: [ ],
    time: serverTimestamp
}
```
I want to display this data on the timeline as a single `item` (so item.content = data), but i dont want it displayed/formatted like below (as in the image example above)
```
{ "items": [ ], "event": "some_event", "time": "serverTimestamp" }
```

I want it displayed/formatted like
```
items: [ ]
event: some_event
time: serverTimestamp
```

The ordering doesnt matter, i just want to display `data` in a more readable way, where each `key: value` is displayed on a new line.

**Comment by guastallaigor** [comment]
I can't test it right now, but have you tried using `scoped-slots`?

That way you could probably format in your end, without using the content attribute

Ref: #53
