### ISSUE TITLE
Add a KEY property to keep track of each item's index easily.

### ISSUE THREAD

**Issue by AbrieJCronje** [guastallaigor/vue-horizontal-timeline#86]
**Is your feature request related to a problem? Please describe.**
In your component, you use `v-for` to loop through `items` and bind the index `i` to `key`, however, as far as I can tell, there is no way to access this index from parent components? I am using slotprops and putting buttons for each `item`, but I want to use the index of each item when the button is clicked to store data related to that specific index's item. (I have considered using item-selected, it will not work in my scenario, as the index is the important bit, not the item.)

**Describe the solution you'd like**
Can a property, `key`, be added that is just a duplicate of the `key` in the `v-for` such that we can use the index of items as desired?

**Describe alternatives you've considered**

**Additional context**

**Comment by AbrieJCronje** [comment]
@guastallaigor 

I solved this by adding a `index` property to the slot in your component and binding it to the v-for's `i` like so:
``` <slot v-if="$scopedSlots.default" v-bind:item="item" v-bind:index="i"/>```

Then in my app, I could access the index as `slotProps.index` as below:

```
<vue-horizontal-timeline 
      title-attr="null"
      :items="someItems.someEvents"
      :item-selected.sync="selectedItem"
      v-bind:has-slot="true"
      v-slot:default="slotProps"
    >
      <template>
         {{ slotProps.item.data }}
        <v-btn 
         @click="clickFunc(slotProps.index)"
        >
      </template>
```

**Comment by guastallaigor** [comment]
I see. Yes, right now the parent component can't access the direct index in the slot. Although, since you are controlling the array of items on the parent component, I'm guessing you have access to the array, its order, therefore all the indexes. 

Another way of doing this is by adding the indexes as a new property inside the items array, which matches the current index.

But, if you need the `:index="i"` in the `<slot>` tag, I can accept a PR.

**Comment by AbrieJCronje** [comment]
@guastallaigor Cool! 

I created a pull request for this issue.

**Comment by guastallaigor** [comment]
ref #87
